import { Language, GameTopic, ModelProvider } from './types';

export const PROVIDER_DEFAULTS: Record<ModelProvider, { label: string; baseUrl: string; defaultModel: string }> = {
  google: { label: 'Google Gemini', baseUrl: '', defaultModel: 'gemini-2.5-flash' },
  openai: { label: 'OpenAI (GPT)', baseUrl: 'https://api.openai.com/v1', defaultModel: 'gpt-4o' },
  deepseek: { label: 'DeepSeek', baseUrl: 'https://api.deepseek.com', defaultModel: 'deepseek-chat' },
  anthropic: { label: 'Anthropic (Claude)', baseUrl: 'https://api.anthropic.com/v1', defaultModel: 'claude-3-5-sonnet-20240620' },
  ollama: { label: 'Ollama (Local)', baseUrl: 'http://localhost:11434/v1', defaultModel: 'llama3' },
  groq: { label: 'Groq', baseUrl: 'https://api.groq.com/openai/v1', defaultModel: 'llama-3.1-70b-versatile' },
};

export const UI_TEXT = {
  [Language.EN]: {
    title: 'Emoji Oracle',
    subtitle: 'Can you decode the AI\'s emoji stories?',
    startGame: 'Start Game',
    dashboard: 'Dashboard',
    settings: 'Settings',
    score: 'Score',
    streak: 'Streak',
    hint: 'Need a Hint?',
    submit: 'Guess',
    next: 'Next Puzzle',
    loading: 'Consulting the Oracle...',
    correct: 'Brilliant! You got it!',
    wrong: 'Not quite. Try again!',
    gameOver: 'Game Over',
    playAgain: 'Play Again',
    topics: {
      [GameTopic.MOVIES]: 'Movies',
      [GameTopic.FOOD]: 'Food',
      [GameTopic.ANIMALS]: 'Animals',
      [GameTopic.ACTIONS]: 'Actions',
      [GameTopic.OBJECTS]: 'Objects',
    },
    settingsTitle: 'Configuration',
    language: 'Language',
    creativity: 'AI Creativity (Temperature)',
    back: 'Back to Home',
    statsTitle: 'Your Journey',
    totalGames: 'Games Played',
    winRate: 'Win Rate',
    bestStreak: 'Best Streak',
    modelConfig: {
      title: 'Model Configuration',
      configList: 'Config List',
      add: 'Add New',
      name: 'Config Name',
      provider: 'Provider',
      apiKey: 'API Key',
      apiKeyPlaceholder: 'Leave empty to use default/env',
      baseUrl: 'API Address (Base URL)',
      modelName: 'Model Name',
      save: 'Save & Close',
      delete: 'Delete',
      selectPrompt: 'Select a configuration to edit',
    }
  },
  [Language.CN]: {
    title: '表情包神谕',
    subtitle: '你能破解 AI 的表情包谜题吗？',
    startGame: '开始游戏',
    dashboard: '数据面板',
    settings: '配置',
    score: '分数',
    streak: '连胜',
    hint: '需要提示吗？',
    submit: '猜一猜',
    next: '下一题',
    loading: '神谕正在生成中...',
    correct: '太棒了！答对了！',
    wrong: '不对哦，再试一次！',
    gameOver: '游戏结束',
    playAgain: '再玩一次',
    topics: {
      [GameTopic.MOVIES]: '电影',
      [GameTopic.FOOD]: '美食',
      [GameTopic.ANIMALS]: '动物',
      [GameTopic.ACTIONS]: '动作',
      [GameTopic.OBJECTS]: '物品',
    },
    settingsTitle: '游戏配置',
    language: '语言',
    creativity: 'AI 创造力 (温度)',
    back: '返回主页',
    statsTitle: '你的战绩',
    totalGames: '游玩次数',
    winRate: '胜率',
    bestStreak: '最高连胜',
    modelConfig: {
      title: '配置 AI 模型',
      configList: '配置列表',
      add: '新建',
      name: '配置名称',
      provider: '服务商',
      apiKey: 'API 密钥',
      apiKeyPlaceholder: '留空以使用默认环境变量 (若已配置)',
      baseUrl: 'API 地址 (Base URL)',
      modelName: '模型名称',
      save: '保存并关闭',
      delete: '删除',
      selectPrompt: '请选择左侧配置进行编辑',
    }
  },
};